config/routes.rb
Rails.application.routes.draw do
  resources :palindromes

  root 'palindromes#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/palindrome.rb
class Palindrome < ApplicationRecord
  validates :number, presence: { message: "Число не задано" }, numericality: { only_integer: true, message: "Это не число" }

  def self.search_id(search)
    select(:id).find_by(number: search) if search
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/palindromes_controller.rb
require 'json'

class String
  def palindrome?
    self == reverse
  end
end

class Integer
  def palindrome?
    to_s.palindrome?
  end
end

class PalindromesController < ApplicationController
  before_action :set_palindrome, only: %i[ show edit update destroy ]

  # Полный список запросов
  def index
    @palindromes = Palindrome.all
    respond_to do |format|
      format.html
      format.json do
        result_array = '[' + @palindromes.inject([]) { |acc, el| acc.append el.result }.join(",\n") + ']'
        render json: result_array
      end
    end
  end

  # Каждый запрос
  def show
  end

  # Для нового запроса
  def new
    @palindrome = Palindrome.new
  end

  # Для редактирования существующего запроса
  def edit
  end

  # Создаёт объект для нового запроса
  def create
    @palindrome = Palindrome.new(palindrome_params)

    @palindrome.result = output(palindrome_params[:number]).to_json if @palindrome.valid?

    id = Palindrome.search_id(palindrome_params[:number])
    if id.nil?
      respond_to do |format|
        if @palindrome.save
          format.html { redirect_to @palindrome, notice: "Palindrome was successfully created." }
          format.json { render :show, status: :created, location: @palindrome }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @palindrome.errors, status: :unprocessable_entity }
        end
      end
    else 
      redirect_to action: 'show', id: id
    end
  end

  # Обновляет данные существующего объекта запроса
  def update
    respond_to do |format|
      if @palindrome.update(palindrome_params)
        format.html { redirect_to @palindrome, notice: "Palindrome was successfully updated." }
        format.json { render :show, status: :ok, location: @palindrome }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @palindrome.errors, status: :unprocessable_entity }
      end
    end
  end

  # Удаляет существующий объект запроса
  def destroy
    @palindrome.destroy
    respond_to do |format|
      format.html { redirect_to palindromes_url, notice: "Palindrome was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_palindrome
      @palindrome = Palindrome.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def palindrome_params
      params.require(:palindrome).permit(:number)
    end

    def output(number)
      result = 0.upto(Integer(number)).select { |number| number.palindrome? && (number**2).palindrome? }

      { 
        values: result.map do |number|
          { result: number, square: number**2 }
        end, 
        length: result.length 
      }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/palindromes_helper.rb
module PalindromesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LR11</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/palindromes/_form.html.erb
<%= form_with(model: palindrome) do |form| %>

  <% if palindrome.errors.any? %>
    <div class="container">
      <div class="alert alert-success" role="alert">
        <h4 class="alert-heading fs-3"> Ошибка при вводе! </h4>
        <p class="fs-5"> Пожалуйста, проверьте ввод </p>
        <hr>
        <% palindrome.errors[:number].each do |error| %>
          <p class="mb-0 fs-5"> <%= error %> </p>
        <% end %>
      </div>
    </div>
  <% end %>
    
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <div class="input-group mb-3">
        <input type="number" class="form-control" id="palindrome_number" name="palindrome[number]" placeholder="Введите число" pattern="[0-9]+" min="0">
        <div class="input-group-append">
          <button class="btn btn-outline-primary" type="submit" name="commit" value="Create Palindrome" data-disable-with="Create Palindrome"> Ввод </button>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/palindromes/edit.html.erb
<h1>Editing Palindrome</h1>

<%= render 'form', palindrome: @palindrome %>

<%= link_to 'Show', @palindrome %> |
<%= link_to 'Back', palindromes_path %>

app/views/palindromes/index.html.erb
<p id="notice"><%= notice %></p>

<section class="py-5 text-center container fst-italic"> 
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light fs-1"> Главная страница </h1>
      <div class="col-12 fs-2">

        <table class="table text-center">
          <thead>
            <tr>
              <th> Число </th>
              <th> Результат </th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @palindromes.each do |palindrome| %>
              <tr>
                <td valign="middle" class="fs-5"><%= palindrome.number %></td>
                <td><%= palindrome.result %></td>
                <td valign="middle" class="fs-5"><%= link_to 'Посмотреть', palindrome %></td>
                <td valign="middle" class="fs-5"><%= link_to 'Удалить', palindrome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <span class="fs-3"> <%= link_to "Добавить новое значение", new_palindrome_path %> </span>
      </div>
    </div>
  </div>
</section>

app/views/palindromes/new.html.erb
<section class="py-5 text-center container fst-italic">
  <h1 class="fw-light fw-bold"> Ввод числа </h1>

  <%= render 'form', palindrome: @palindrome %>

  <span class="fs-3"> <%= link_to "Назад (к главной странице)", palindromes_path %> </span>
</section>

app/views/palindromes/show.html.erb
<p id="notice"><%= notice %></p>

<section class="py-5 text-center container fst-italic"> 
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light fs-1"> Результат </h1>
      <p class="lead text-muted"> Числа, сами являющиеся палиндромами и при возведении в квадрат, образующие палиндромы (до <%= @palindrome.number %>).</p>
      <div class="col-12 fs-3">

        <table class="table text-center">
          <thead>
            <tr>
              <th> Число </th>
              <th> Квадрат числа </th>
            </tr>
          </thead>
          <tbody>
            <% if (@palindrome.result) %>
              <% JSON.parse(@palindrome.result)['values'].each do |element| %>
                <tr>
                  <td class="fs-4"> <%= element['result'] %> </td>
                  <td class="fs-4"> <%= element['square'] %> </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text fs-4"> Количество чисел: </span>
          </div>
          <input type="text" class="form-control fs-4" id="Result" placeholder="Количество чисел" value="<%= JSON.parse(@palindrome.result)['length'] if @palindrome.result %>" readonly>
        </div>
        <span class="fs-3"> <%= link_to "Назад (к главной странице)", palindromes_path %> </span>
      </div>
    </div>
  </div>
</section>